### ISSUE TITLE
APK Compiler

### ISSUE THREAD

**Issue by matthew4444** [LostTeam/Kill-the-Dragon#1]
https://www.google.com/search?q=apk+compiler&oq=apk+compile&aqs=chrome.1.69i59j0j69i57j69i60j0l2.6937j0j4&sourceid=chrome&espv=2&es_sm=91&ie=UTF-8

**Comment by jasonwynn10** [comment]
This is the most unhelpful link that you could have posted. Anyone can search google for things.

**Comment by MCUnderground** [comment]
There should be apk, go to bin folder @matthew4444
